FROM fedora:42

ENV INTERVAL=1d
ENV PYTHONUNBUFFERED=1
ENV ENABLE_SERVER_REPO=0

RUN dnf -y update && \
    dnf -y install \
    desktop-file-utils \
    python3 \
    make \
    rpm-build \
    rpmdevtools \
    binutils \
    gtk-update-icon-cache \
    util-linux \
    httpd \
    createrepo \
    && dnf clean all \
    && rm -f /etc/httpd/conf.d/welcome.conf \
    && sed -i "s/User apache/User spotify/" /etc/httpd/conf/httpd.conf \
    && sed -i "s/Group apache/Group spotify/" /etc/httpd/conf/httpd.conf \
    && sed -i 's|/var/www/html|/data|' /etc/httpd/conf/httpd.conf

WORKDIR /build

COPY scripts/* .
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /build/start.sh /entrypoint.sh

VOLUME [ "/data" ]

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/build/start.sh"]