FROM fedora:42

ENV INTERVAL=1d
ENV PYTHONUNBUFFERED=1

RUN dnf -y update && \
    dnf -y install \
    desktop-file-utils \
    python3 \
    make \
    rpm-build \
    rpmdevtools \
    binutils \
    gtk-update-icon-cache \
    && dnf clean all

WORKDIR /build

COPY scripts/* .

RUN chmod +x /build/start.sh

CMD ["/build/start.sh"]