server {
    listen 80 default_server;
    listen [::]:80 default_server;    
    server_name _;
    return 444;

    access_log /logs/nginx-default_server-access.log main;
    error_log /logs/nginx-default_server-error.log warn;
}